### ISSUE TITLE
sklearn-server ROCK should implement a second Dockerfile too

### ISSUE THREAD

**Issue by orfeas-k** [canonical/seldonio-rocks#44]
During updating Seldon ROCKs for CKF 1.8 https://github.com/canonical/seldonio-rocks/issues/37, we concluded with @i-chvets that current [rockcraft.yaml file](https://github.com/canonical/seldonio-rocks/blob/main/sklearnserver/rockcraft.yaml) is based on upstream [Dockerfile.conda](https://github.com/SeldonIO/seldon-core/blob/v1.16.0/wrappers/s2i/python/Dockerfile.conda) and doesn't take into account the [Dockerfile](https://github.com/SeldonIO/seldon-core/blob/v1.16.0/wrappers/s2i/python/Dockerfile). Looking at the upstream [Makefile](https://github.com/SeldonIO/seldon-core/blob/v1.16.0/wrappers/s2i/python/Makefile#L30-L33) though, we see that in order to build their image, they use both (with Dockerfile.conda as a `BASE_IMAGE`). Thus, we need to implement the other Dockerfile into our ROCK as well.

**Comment by kimwnasptd** [comment]
@orfeas-k how was it concluded that our `rockcraft.yaml` file was only using `Dockerfile.conda` as "base" and not the `Dockerfile` produced image?

**Comment by orfeas-k** [comment]
So what is going on in upstream:
- server image is built using s2i tool https://github.com/SeldonIO/seldon-core/blob/v1.17.1/servers/sklearnserver/Makefile#L7-L12
- s2i build_all command first builds conda base image and then simple and cpu image https://github.com/SeldonIO/seldon-core/blob/v1.17.1/wrappers/s2i/python/build_scripts/build_all.sh
- simple image builds using conda image as `base_image` https://github.com/SeldonIO/seldon-core/blob/v1.17.1/wrappers/s2i/python/Makefile#L29-L31 and https://github.com/SeldonIO/seldon-core/blob/v1.17.1/wrappers/s2i/python/Dockerfile#L1-L3
which means that our rockcraft.yaml should implement all of this (including `Dockerfile` and `Dockerfile.conda`).

Looking at our rockcraft.yaml though, we notice that [these](https://github.com/SeldonIO/seldon-core/blob/822053e7bbc897f34d84aaf5892d5947163249c5/wrappers/s2i/python/Dockerfile#L30-L34) are never installed. This hasn't created a problem to us until now since there is chance that our tests do not use any of the things from [python directory](https://github.com/SeldonIO/seldon-core/tree/v1.17.1/python).

**Comment by SamirPS** [comment]
Hello,

the base image used on the ```Dockerfile``` is ``docker.io/seldonio/conda-ubi8`` which depend on this docker build : https://github.com/SeldonIO/seldon-core/blob/v1.16.0/wrappers/s2i/python/Makefile#L79C18-L79C34 so yes the Dockerfile need Dockerfile.conda

**Comment by SamirPS** [comment]
for me your rockcraft.yaml file is a mix of both.

because you create a microservice folder witch is only on Dockerfile, but you don't move out the s2i/bin for example
